### ISSUE TITLE
"Dafny program verifier is running..." but nothing happens.

### ISSUE THREAD

**Issue by johanews** [Alchiadus/dafny-workbench#2]
Hi, I use Mac and I have mono installed on my computer. The executable path points to my "dafny" folder (I downloaded the official releases for Mac OS X). I can run the programs via the terminal but not in Atom. The verifier is running but nothing happens. I guess it's because I'm using a wrapper script, but where exactly do I make us of the lines below?

#!/usr/bin/env bash
mono /path/to/Dafny.exe $*

**Comment by Alchiadus** [comment]
That's the contents of the script that `dafny-workbench` should call to launch the official Dafny release. You are free to name and place it anywhere you like (provided your user has the right permissions, of course). Suppose the location will be `~/bin/dafny`:

1. Create `~/bin/dafny` with the following contents:
```bash
#!/usr/bin/env bash
mono /path/to/Dafny.exe $*
```
2. Make sure it's executable.
```bash
chmod +x ~/bin/dafny
```
3. Open Atom and go to ` dafny-workbench`'s settings. Change the `dafnyExecutablePath` setting to: `~/bin/dafny`.

**Comment by johanews** [comment]
Thank you for your swift response, now it's working perfectly!

**Comment by Alchiadus** [comment]
Happy to help, glad it's resolved!
